# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rprocfs}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Valentin Mihov"]
  s.date = %q{2009-10-12}
  s.description = %q{A library, which allows easily reading various process stats from the proc filesystem}
  s.email = %q{valentin.mihov@gmail.com}
  s.extensions = ["ext/rprocfs/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "ext/rprocfs/extconf.rb",
     "ext/rprocfs/native.c",
     "lib/rprocfs.rb",
     "lib/rprocfs/stat.rb",
     "lib/rprocfs/stat_m.rb",
     "rprocfs.gemspec",
     "spec/rprocfs/stat.rb",
     "spec/rprocfs/statm.rb",
     "spec/rprocfs_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/valo/rprocfs}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby proc filesystem interface}
  s.test_files = [
    "spec/rprocfs/stat.rb",
     "spec/rprocfs/statm.rb",
     "spec/rprocfs_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
